version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: discussion_board_db
    environment:
      POSTGRES_DB: ${DB_NAME:-discussion_board}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: discussion_board_api
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./backend/.env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-discussion_board}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      DB_SSL: ${DB_SSL:-false}
      DB_POOL_MAX: ${DB_POOL_MAX:-10}
      DB_POOL_MIN: ${DB_POOL_MIN:-2}
      DB_POOL_ACQUIRE: ${DB_POOL_ACQUIRE:-30000}
      DB_POOL_IDLE: ${DB_POOL_IDLE:-10000}
      DB_STATEMENT_TIMEOUT: ${DB_STATEMENT_TIMEOUT:-30000}
    ports:
      - "3000:3000"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:8.2
    container_name: discussion_board_pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@example.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 'False'
      PGADMIN_CONFIG_COOKIE_DEFAULT_SECURE: 'False'
      PGADMIN_CONFIG_COOKIE_SAMESITE: '"Lax"'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    # This entrypoint ensures permissions are fixed before pgAdmin starts
    entrypoint: >
      sh -c "
        echo 'Fixing pgAdmin volume permissions...';
        chmod -R 775 /var/lib/pgadmin || true;
        chown -R 5050:5050 /var/lib/pgadmin || true;
        exec /entrypoint.sh;
      "
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - pgadmin_config:/var/lib/pgadmin/storage
    restart: unless-stopped

volumes:
  postgres_data:
  pgadmin_data:
  pgadmin_config:

